services:
  - type: web
    name: bot-ia-front
    env: node
    buildCommand: |
      npm install
      ./node_modules/.bin/ng build --configuration production
    startCommand: npx http-server ./dist/bot-ia -p 8080
