services:
  - type: web
    name: bot-ia-front
    env: node
    buildCommand: |
      npm install
      npx ng build --configuration production
    startCommand: npx http-server ./dist/bot-ia/browser -p 8080
