services:
  - type: web
    name: bot-ia-front
    env: node
    buildCommand: |
      npm install
      npx ng build --configuration production
    startCommand: npx serve ./dist/bot-ia/browser -l $PORT
