name: Deploy AnalytiCode

on:
  push:
    branches:
      - main

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.1'

      - name: Install dependencies
        run: |
         npm install
          npm install -g @angular/cli
          ng version

      - name: Build the project
        run: npx ng build --configuration production

      - name: Deploy AnalytiCode
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
          -H 'Authorization: Bearer $RENDER_API_KEY' \
          -H 'Content-Type: application/json' \
          -d '{
            "serviceId": "$SERVICE_ID",
            "branch": "main"
          }' \
          https://api.render.com/v1/services/$SERVICE_ID/deploys
